### ISSUE TITLE
Repeats over imports not working

### ISSUE THREAD

**Issue by astrolamb-gaming** [dougreichard/artemis_macro_language#2]
GIven the following:
```
	<range name="SystemNames">
		<value system="Promethean"/>
		<value system="Cerberus"/>
	</range>
```
```
  <imports>
	<repeat _range="SystemNames" _as="sys">
		<import name="${sys.system}.xml"/>
	</repeat>
	<import name="Promethean.xml"/>
  </imports>
```
The `import name="Promethean.xml"/>` bit works correctly, but importing systems from a range doesn't work. That would be a tremendous help for the TSN RP Community's sandbox, which currently has over 30 systems.

Also tested this, same result:
```
  <imports>
	<repeat _range="SystemNames">
		<import name="${system}.xml"/>
	</repeat>
	<import name="Promethean.xml"/>
  </imports>
```

It would also be awesome to have a variant of the repeat that allowed using the `_as=""` like so:
```
<repeat _length="5" _as="x">
  <repeat _length="5" _as="y">
    <!-- use ${x} and ${y} as needed-->
  </repeat>
</repeat>
```

**Comment by astrolamb-gaming** [comment]
Could you also expand on the documentation for templates. I'm quite unclear how to use/set them up.

**Comment by dougreichard** [comment]
You are correct. I did not anticipate using repeat with the import section. Looking at the code I think I can add that.

I'll also look at the _length / _as. Also something I did not consider.

Regarding documentation, yes documentation could be better and there is a lot of depth to Templates and Template Strings that is hard to show the power of it all.

I was hoping a community would grow with templates and libraries, but it does require people understanding it.

**Comment by dougreichard** [comment]
**Added repeats in imports**
Test:
https://github.com/dougreichard/artemis_macro_language/blob/master/test/fragments/xml/import-repeat-fragment.xml
Generates:
https://github.com/dougreichard/artemis_macro_language/blob/master/test/fragments/xml/expected/import-repeat-fragment.xml

**Added _as with _length to use index value** 
Test:
https://github.com/dougreichard/artemis_macro_language/blob/master/test/fragments/xml/repeat-as-index-fragment.xml

Generates:
https://github.com/dougreichard/artemis_macro_language/blob/master/test/fragments/xml/expected/repeat-as-index-fragment.xml

**Comment by astrolamb-gaming** [comment]
If you were to give me some perms for documentation I could probably add to it with what I've learned from experimentation.

**Comment by dougreichard** [comment]
It would help a lot. You can fork the github repo, make changes and then
submit a pull request.

Do you need something more than that?

I did follow a 1) Make it work 2) Develop tests 3) Develop Bigger examples
4) and do enough docs to get it out
So yeah the documentations need work. I was gauging if anyone would even
use it to see how much more effort to put in.

I just posted a new video that decomposes a partial script with steps that
go from full script to a custom tag using templates.
It is very simplified though. Doesn't use params for example.

https://youtu.be/UvjvdRsSJ40

The steps from the tutorial are here, and could be a starting point for
either of us.
https://github.com/dougreichard/artemis_macro_language/tree/master/examples/whales/video

**Comment by astrolamb-gaming** [comment]
The tutorial video is good. I may do a bit of expanding on templates and such if I have a few minutes.
I have another request btw (is there a better place for these discussions? Gitter.im, perhaps?):
Within a template, it would be great if we could use a template's param(s) as values for repeats and such, i.e.:
```
		<template name="GM_Buttons">
			<params>
				<param name="x_across"/>
				<param name="y_across"/>
				<param name="x_start"/>
				<param name="y_start"/>
				<param name="x_gap"/>
				<param name="y_gap"/>
				<param name="h"/>
				<param name="w"/>
			</params>
			<repeat _length="${y_across}" _as="y"> 
				<repeat _length="${x_across}" _as="x">
					<set_gm_button text="Sector ${y*x_across + x + 1}" x="${w*x + x_gap*x + x_start}" y="${y+y_start}" h="${h}" w="${w}" />
				</repeat>
			</repeat>
		</template>
```
Where the y_across and x_across values are passed to the _length attribute. 

A separate issue, in the set_gm_button node, the value of the text attribute correctly parses, but I've yet to find a way to get the x and y attribute calculations to work correctly. It seems to be taking the values for each of the sections between the + sign and appending them together. y being the simpler example(where y_start is 190), outputs "0190", "1190", and so on. 
More testing:
Given:
```
		<expand _template="GM_Buttons"
			x_across="5"
			y_across="5"
			x_start="170"
			y_start="190"
			x_gap="5"
			y_gap="5"
			w="60"
			h="60"/>
```
`${x_gap*w}` outputs 300, as is expected.
`${x_gap+w}` outputs 560, which is not.
`${x_gap+5}` outputs 55.
`{x_gap*x}` outputs 0, 5, 10, 15, and 20 as expected
`${x_gap*x + x_gap}` outputs 05, 55, 105, 155, 205.
`${x_gap*x + x}` outputs 0, 6, 12, 18, 24, as expected.
`${x_gap*x + x*x_gap}` outputs 0, 10, 20, 30, 40.
The pattern here seems to be that addition only works when the values being added are either one of the index(es), or a multiple of the index(es)

**Comment by dougreichard** [comment]
are you on the artemis forums? I'm not, but I could if you think that would
be a better place to have this thread and others.

regarding using variables as numbers.
The underlying tech behind the template string is javascript and it is
receiving strings.

It is difficult to assume you want strings, integers or floating point
numbers.

There are functions to convert to the strings to number
_.int()
_.float()

For example:

 ${_.int(y) * _.int(x_across) + _.int(x) + 1}


there is also _.map() to convert
<value x="${_.map.x(2.3)}" y="0.0" z="${_.map.z('B.25')}" navpoint="NAV_01"
/>

So x is about 1/3 in on grid 2 and a quarter way down in the B line

The thought with the map you can think about where on the map and not have
to think about converting the value yourself.

Using javascript it is even possible to extend what is available to
template strings.

I originally did persistence as a plugin, but later built it in.
The built in reads the log file and uses the data from the previous run
when regenerating the script.

So...yeah there is a lot to document.

**Comment by dougreichard** [comment]
You're right repeat _length is NOT expanding.
I updated version 0.6 to 0.6a it should have the _length fix.
<mission_data version="1.0">
  <templates>
    <template name="tsn:GM_Buttons">
            <params>
                <param name="x_across"/>
                <param name="y_across"/>
                <param name="x_start"/>
                <param name="y_start"/>
                <param name="x_gap"/>
                <param name="y_gap"/>
                <param name="h"/>
                <param name="w"/>
            </params>
            <repeat _length="${y_across}" _as="y">
                <repeat _length="${x_across}" _as="x">
                    <set_gm_button text=
"Sector ${_.int(y)*_.int(x_across)+_.int(x)+1}" x=
"${_.int(w)*_.int(x)+_.int(x_gap)*_.int(x)+_.int(x_start)}" y=
"${_.int(y) +_.int(y_start)}" h="${h}" w="${w}" />
                </repeat>
            </repeat>
        </template>
    </templates>

  <start>
    <tsn:GM_Buttons x_across="5" y_across="2" x_start="100" y_start="200"
x_gap="3" y_gap="2" h="10" w="100" />
  </start>
</mission_data>


GENERATES

<mission_data version="1.0">
  <start>
    <set_gm_button text="Sector 1" x="100" y="200" h="150" w="20"/>
    <set_gm_button text="Sector 2" x="280" y="200" h="150" w="20"/>
    <set_gm_button text="Sector 3" x="460" y="200" h="150" w="20"/>
    <set_gm_button text="Sector 4" x="640" y="200" h="150" w="20"/>
    <set_gm_button text="Sector 5" x="820" y="200" h="150" w="20"/>
    <set_gm_button text="Sector 6" x="100" y="201" h="150" w="20"/>
    <set_gm_button text="Sector 7" x="280" y="201" h="150" w="20"/>
    <set_gm_button text="Sector 8" x="460" y="201" h="150" w="20"/>
    <set_gm_button text="Sector 9" x="640" y="201" h="150" w="20"/>
    <set_gm_button text="Sector 10" x="820" y="201" h="150" w="20"/>
  </start>
</mission_data>

**Comment by dougreichard** [comment]
I signed up for the artemis forums.
