### ISSUE TITLE
Using a <value> name in import not working

### ISSUE THREAD

**Issue by astrolamb-gaming** [dougreichard/artemis_macro_language#4]
Given the following:

``` xml
<values>
    <value system="Sol"/>
</values>
<imports>
    <import name="Systems/${system}.xml"/>
</imports>
```

AML returns an error: 

`ERROR: ENOENT: no such file or directory, open '....\Systems\${system}.xml' ....\Systems\${system}.xml`

Changing to `<import name="Systems/Sol.xml"/>` works just fine.

Similarly, if I have a json file that defines a list of systems:
``` json
{
   "systems" : [
       {"system" : "Sol"}
   ]
}
```

Upon importing, it replaces the values of `<range name="systems">...` only after all the imports are done. So I can't do the following:
``` xml
<imports>
    <import name="systems.json"/>
    <repeat _range="systems">
        <import name="${system}.xml"/>
    </repeat>
</imports>
```
Or rather, I can, but the original values of the system range are used, not the updated ones from the json file.

**Comment by dougreichard** [comment]
Try:


<imports>

    <expand><import name="Systems/${system}.xml"/></expand>
</imports>

**Comment by astrolamb-gaming** [comment]
That does work for the first bit there, thanks. The second bit, with using imported values for use in the next import, still doesn't unfortunately.

**Comment by dougreichard** [comment]
I released v0.7 which does a better job of handling template string within import.
Both cases you mentioned should now work. i.e. you shouldn't need to surround with <expand> and it will use values from an previously imported file.

**Comment by astrolamb-gaming** [comment]
My testing indicates that while regular values are correctly updated with an import, ranges are not.

Since this is about imports I'll also note here that when a js file is imported, I can't call a function to use with `_skip` in a later import, no idea how difficult that one would be to fix.

**Comment by dougreichard** [comment]
Ok Version 0.8 should fix everything you've been asking for. I see now I was trying for quick fixes, and now I've gone and reworked it properly. 
- repeats including nested work with import
- you do not need to wrap imports in expand
- plugins are accessible in processing imports

I'm not certain but processing repeat may be faster as well.
